services:
  cyber-scanner:
    build: .
    container_name: cyber_github_scanner
    restart: always
    expose:
      - "8000"
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cyberscan.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.cyberscan.tls=true"
      - "traefik.http.routers.cyberscan.tls.certresolver=letsencrypt"
      - "traefik.http.services.cyberscan.loadbalancer.server.port=8000"

networks:
  proxy:
    external: true
